### ISSUE TITLE
[BUG] requests actually required in version 1.1.0, but not listed as install_requires

### ISSUE THREAD

**Issue by sfoster3** [opensearch-project/opensearch-py#141]
**What is the bug?**
opensearch-py version 1.1.0 does not list `requests` as an install_requirement, but requires requests.

**How can one reproduce the bug?**
1. install opensearch-py 1.1.0 `pip install opensearch-py` into an env that does not have `requests` installed
2. Import opensearch `from opensearchpy import OpenSearch` or `import opensearchpy`
3. See that the import fails as follows:
`>>> from opensearchpy import OpenSearch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/samfoster/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opensearchpy/__init__.py", line 64, in <module>
    from .helpers import AWSV4SignerAuth
  File "/Users/samfoster/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opensearchpy/helpers/__init__.py", line 40, in <module>
    from .signer import AWSV4SignerAuth
  File "/Users/samfoster/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opensearchpy/helpers/signer.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**What is the expected behavior?**
opensearch should import cleanly. I believe just adding `requests` to the `install_requires` block in setup.py would suffice.

**What is your host/environment?**
 - OS: macOs
 - Version 10.15.7
 - Python 3.8.0

**Comment by wbeckler** [comment]
The PR was merged. Unless there are any objections I will close this issue.
