### ISSUE TITLE
[BUG] CI tests are not working locally

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#267]
### What is the bug?
CI tests are not working locally.

### What is the expected behavior?
Fix the CI tests such that it works locally.

**Comment by saimedhi** [comment]
Working on it.

**Comment by saimedhi** [comment]
`nox > Running session test-3.9
nox > Re-using existing virtual environment at .nox/test-3-9.
nox > python -m pip install .
nox > python -m pip install -r dev-requirements.txt
nox > python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running egg_info
writing opensearch_py.egg-info/PKG-INFO
writing dependency_links to opensearch_py.egg-info/dependency_links.txt
writing requirements to opensearch_py.egg-info/requires.txt
writing top-level names to opensearch_py.egg-info/top_level.txt
reading manifest file 'opensearch_py.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Changelog.rst'
warning: no files found matching 'LICENSE'
no previously-included directories found matching 'test_opensearch'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
adding license file 'LICENSE.txt'
adding license file 'NOTICE.txt'
adding license file 'AUTHORS'
writing manifest file 'opensearch_py.egg-info/SOURCES.txt'
running build_ext
GET https://localhost:9200/ [status:N/A request:0.029s]
Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/connection/http_urllib3.py", line 240, in perform_request
    response = self.pool.urlopen(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
GET https://localhost:9200/ [status:N/A request:0.011s]
Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/connection/http_urllib3.py", line 240, in perform_request
    response = self.pool.urlopen(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
GET https://localhost:9200/ [status:N/A request:0.012s]
Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/connection/http_urllib3.py", line 240, in perform_request
    response = self.pool.urlopen(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
GET https://localhost:9200/ [status:N/A request:0.012s]
Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/connection/http_urllib3.py", line 240, in perform_request
    response = self.pool.urlopen(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/connection/http_urllib3.py", line 240, in perform_request
    response = self.pool.urlopen(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimedhi/code3/opensearch-py/setup.py", line 71, in <module>
    setup(
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/command/test.py", line 224, in run
    self.run_tests()
  File "/Users/saimedhi/code3/opensearch-py/.nox/test-3-9/lib/python3.9/site-packages/setuptools/command/test.py", line 227, in run_tests
    test = unittest.main(
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/saimedhi/opt/anaconda3/lib/python3.9/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
  File "/Users/saimedhi/code3/opensearch-py/test_opensearchpy/run_tests.py", line 91, in run_all
    fetch_opensearch_repo()
  File "/Users/saimedhi/code3/opensearch-py/test_opensearchpy/run_tests.py", line 57, in fetch_opensearch_repo
    from test_opensearchpy.test_server import get_client
  File "/Users/saimedhi/code3/opensearch-py/test_opensearchpy/test_server/__init__.py", line 30, in <module>
    from opensearchpy.helpers import test
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/helpers/test.py", line 112, in <module>
    OPENSEARCH_VERSION = opensearch_version(client)
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/helpers/test.py", line 103, in opensearch_version
    return _get_version(client.info()["version"]["number"])
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/client/utils.py", line 178, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/client/__init__.py", line 251, in info
    return self.transport.perform_request(
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/transport.py", line 406, in perform_request
    raise e
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/transport.py", line 369, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/saimedhi/code3/opensearch-py/opensearchpy/connection/http_urllib3.py", line 252, in perform_request
    raise SSLError("N/A", str(e), e)
opensearchpy.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129))
nox > Command python setup.py test failed with exit code 1
nox > Session test-3.9 failed.`
