### ISSUE TITLE
[BUG] OpenSearch-Py throws error despite total copies being a multiple of total awareness attributes

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-py#411]
### What is the bug?
OpenSearch-Benchmark (OSB) uses opensearch-py client under the hood to perform CRUD operations on a target cluster. OSB has a mechanism that allows users to set the number of primary shards and number of replica shards. For example, when OSB users set the config to `number_of_shards = 9` and `number_of_replicas = 1` for a single node cluster with 1 AZ, OSB creates the indices accordingly. 
```
### Indices in single node 1AZ OpenSearch cluster
health status index                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   benchmark-metrics-2023-06         9JB1Ua3DRvW99DwokDyziA   9   1        280            0    779.2kb        779.2kb
yellow open   benchmark-results-2023-06         hhIrNV3KR4C7_kXS0_hkqg   9   1        184            0    152.3kb        152.3kb
yellow open   benchmark-test-executions-2023-06 0Kt0nFtJSTmHJ5llmjMIYA   9   1         27            0     57.6kb         57.6kb
```
However, when we apply the same config settings and run it with a multi node cluster (3 Master Nodes and 3 Data Nodes) with 3 AZs, opensearch-py throws the following error, preventing OSB from creating the indices:
```
opensearchpy.exceptions.RequestError: RequestError(400, 'invalid_index_template_exception', 'index_template [benchmark-metrics] invalid, cause [Validation Failed: 1: expected total copies needs to be a multiple of total awareness attributes [3];]')
```
It only works when we use the following config option `number_of_replicas = 2` or set it to None, in which it uses the `default_number_of_replicas` from the `/_cluster/settings`. 

It's worth noting that the `default_number_of_replicas` in our multi node cluster is `2`, which contrasts with the OpenSearch documentation that states [that the default number of replicas should be 1](https://opensearch.org/docs/latest/im-plugin/index-templates/#template-2). This is because the cluster is a cloud-managed service cluster, which was automatically provisioned and comes with the following default setting that we cannot change:
```
$ cat settings_2.json | grep "number_of_replicas"
      "default_number_of_replicas" : "2",
          "number_of_replicas" : "1",
          "number_of_replicas" : "1",
```

Based on my understanding, the total number of copies can be found with `number of shards * (number of replicas + 1)`. In this case, it'd be `18` (9 * (1 + 1)), which is a multiple of 3. I've also tested it it with `number_of_replicas` set to 3 and error still occurs. 

### Question:
Am I misunderstanding this error or is this a bug in OpenSearch-py? Or is this happening strictly because of the `"default_number_of_replicas" : "2"` setting found in the cluster? 

### How can one reproduce the bug?
1. Create a multi node cluster with 3AZs and ensure that settings has`"default_number_of_replicas" : "2",` (can verify by running a curl command with `?pretty&include_defaults` appended at the end.
2. Use OpenSearch-py client to create an index in the multi node cluster

I can also provide a forked copy of OSB where the latest code that's testing this exists. 

### What is the expected behavior?
Error should not be thrown as `18` is a multiple of 3. 

### What is your host/environment?
Shouldn't matter in this situation since running against an external cluster but running the client on my local machine, which is a MacOS/X86 

### Do you have any screenshots?
Provided the log snippet above but here is the larger snippet of OSB's logs:
```
2023-06-15 17:49:12,926 ActorAddr-(T|:60576)/PID:86489 osbenchmark.actor ERROR Error in test execution orchestrator
Traceback (most recent call last):

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/metrics.py", line 120, in guarded
    return target(*args, **kwargs)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/client/indices.py", line 631, in put_template
    return self.transport.perform_request(

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/transport.py", line 412, in perform_request
    raise e

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/transport.py", line 373, in perform_request
    status, headers_response, data = connection.perform_request(

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 282, in perform_request
    self._raise_error(response.status, raw_data)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(

opensearchpy.exceptions.RequestError: RequestError(400, 'invalid_index_template_exception', 'index_template [benchmark-metrics] invalid, cause [Validation Failed: 1: expected total copies needs to be a multiple of total awareness attributes [3];]')

```

**Comment by wbeckler** [comment]
This looks like an issue with OpenSearch core, not with the python client.  You're gettting a 400 response from the server. Do you want to transfer this to opensearch core repo?

**Comment by saimedhi** [comment]
@IanHoang, In opensearch-py, I didn't find any documentation recommending the following rule: "expected total copies must be a multiple of total awareness attributes [3];]." I don't think the problem is with opensearch-py. The error is coming from opensearch core.

**Comment by dblock** [comment]
I'll close this here, but feel free to reopen if you're convinced this is an issue with the client.

**Comment by IanHoang** [comment]
@wbeckler @saimedhi @dblock Makes sense. Thanks for taking a look at this. I've opened up a issue in OpenSearch core repository: https://github.com/opensearch-project/OpenSearch/issues/8205
